// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type AccountInput struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	MobilePhone *string `json:"mobilePhone"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Location struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	GoogleAccountID  *string     `json:"googleAccountId"`
	GoogleLocationID *string     `json:"googleLocationId"`
	PlaceID          *string     `json:"placeId"`
	StoreCode        *string     `json:"storeCode"`
	Description      *string     `json:"description"`
	Address          *string     `json:"address"`
	ZipCode          *string     `json:"zipCode"`
	Phone            *string     `json:"phone"`
	WebsiteURL       *string     `json:"websiteURL"`
	PhotoURL         *string     `json:"photoURL"`
	Category         []*Category `json:"category"`
	Coordinates      []float64   `json:"coordinates"`
	BusinessAccount  *string     `json:"businessAccount"`
	IsVerified       *bool       `json:"isVerified"`
	IsPublished      *bool       `json:"isPublished"`
	IsActive         *bool       `json:"isActive"`
}

type OrderInput struct {
	AccountID string               `json:"accountId"`
	Products  []*OrderProductInput `json:"products"`
}

type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type PaginationInput struct {
	Skip *int `json:"skip"`
	Take *int `json:"take"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
